default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 16 %>

development:
  <<: *default
  database: desman

test:
  <<: *default
  database: db/desman-test

production:
  <<: *default
  database: desman
