default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 16 %>

development:
  <<: *default
  database: desman

test:
  <<: *default
  database: desman

production:
  <<: *default
  database: desman
